classDiagram
direction LR


class Aeropuerto {
  +int IdAeropuerto
  +string CodigoAeropuerto
  +string Nombre
  +string Ciudad
  +string Pais
  +bool Activo
}

class Ruta {
  +int IdRuta
  +int IdAeropuertoOrigen_FK
  +int IdAeropuertoDestino_FK
  +string CodigoVuelo
  +int DuracionMin
  +bool Activo
}

class Aeronave {
  +int IdAeronave
  +int IdAerolinea_FK
  +string Matricula
  +string Modelo
  +int Capacidad
  +bool Activo
}

class Salida {
  +int IdSalida
  +int IdRuta_FK
  +int IdAeronave_FK
  +date FechaSalida
  +date FechaLlegada
  +string Estado
}

Aeropuerto "1" --> "0..*" Ruta : origen/destino
Ruta "1" --> "0..*" Ruta : programada
Aeronave "1" --> "0..*" Salida : asignada
